services:
  app:
    build:
      context: .
    image: employee-app
    container_name: employee-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/employee_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - KEYCLOAK_URL=http://keycloak:8080
    depends_on:
      - db
      - keycloak
    networks:
      - app-network
    ports:
      - "8083:8083"

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  keycloak:
    image: keycloak/keycloak:23.0.4
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-employee.json
    ports:
      - "8082:8080"
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./realm-employee.json:/opt/keycloak/data/import/realm-employee.json
    networks:
      - app-network
    depends_on:
      - db

volumes:
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge
