package by.andersen.employee.exception;

public enum ErrorMessage {
    WORKER_NOT_FOUND,
    MANAGER_NOT_FOUND,
    OTHER_WORKER_NOT_FOUND,
    EMPLOYEE_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    EMPLOYEE_NOT_FOUND_FOR_MANAGER,
    SELF_SUBORDINATION_NOT_ALLOWED
}
