server:
  port: ${EMPLOYEE_APP_PORT}

spring:
  datasource:
    password: ${EMPLOYEE_APP_DB_PASSWORD}
    username: ${EMPLOYEE_APP_DB_USERNAME}
    url: ${EMPLOYEE_APP_DB_URL}
  liquibase:
    change-log: classpath:/liquibase/changelog-master.yml
  jpa:
    open-in-view: false

jwt:
  auth:
    converter:
      resource-id: employee-client
      principal-attribute: principal_username

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUE_URL}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs




