server:
  port: ${EMPLOYEE_APP_PORT}

spring:
  datasource:
    password: ${EMPLOYEE_APP_DB_PASSWORD}
    username: ${EMPLOYEE_APP_DB_USERNAME}
    url: ${EMPLOYEE_APP_DB_URL}
  liquibase:
    change-log: classpath:/liquibase/changelog-master.yml
  jpa:
    open-in-view: false




