server:
  port: 8083

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/employee-realm



